
notspot_controller:
  
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 25

  # FL Controllers ------------------------------------------------------------ 
  front_left_shoulder:
      type: effort_controllers/JointPositionController
      joint: front_left_shoulder
      pid: {p: 9, i: 0.03, d: 0.3055, i_clamp_min:  -1000, i_clamp_max: 1000}
        
  front_left_foot:
      type: effort_controllers/JointPositionController
      joint: front_left_foot
      pid: {p: 9, i: 0.03, d: 0.3055, i_clamp_min:  -1000, i_clamp_max: 1000}
        
  front_left_leg:
      type: effort_controllers/JointPositionController
      joint: front_left_leg
      pid: {p: 9, i: 0.03, d: 0.3055, i_clamp_min:  -1000, i_clamp_max: 1000}

  # FR Controllers ------------------------------------------------------------ 
  front_right_shoulder:
      type: effort_controllers/JointPositionController
      joint: front_right_shoulder
      pid: {p: 9, i: 0.03, d: 0.3055, i_clamp_min:  -1000, i_clamp_max: 1000}
        
  front_right_foot:
      type: effort_controllers/JointPositionController
      joint: front_right_foot
      pid: {p: 9, i: 0.03, d: 0.3055, i_clamp_min:  -1000, i_clamp_max: 1000}
        
  front_right_leg:
      type: effort_controllers/JointPositionController
      joint: front_right_leg
      pid: {p: 9, i: 0.03, d: 0.3055, i_clamp_min:  -1000, i_clamp_max: 1000}

  # RR Controllers ------------------------------------------------------------ 
  rear_right_shoulder:
      type: effort_controllers/JointPositionController
      joint: rear_right_shoulder
      pid: {p: 9, i: 0.03, d: 0.3055, i_clamp_min:  -1000, i_clamp_max: 1000}
        
  rear_right_foot:
      type: effort_controllers/JointPositionController
      joint: rear_right_foot
      pid: {p: 9, i: 0.03, d: 0.3055, i_clamp_min:  -1000, i_clamp_max: 1000}
        
  rear_right_leg:
      type: effort_controllers/JointPositionController
      joint: rear_right_leg
      pid: {p: 9, i: 0, d: 0.3055, i_clamp_min:  -1000, i_clamp_max: 1000}

  # RL Controllers ------------------------------------------------------------     
  rear_left_shoulder:
      type: effort_controllers/JointPositionController
      joint: rear_left_shoulder
      pid: {p: 9, i: 0.03, d: 0.3055, i_clamp_min:  -1000, i_clamp_max: 1000}
        
  rear_left_foot:
      type: effort_controllers/JointPositionController
      joint: rear_left_foot
      pid: {p: 9, i: 0.03, d: 0.3055, i_clamp_min:  -1000, i_clamp_max: 1000}
        
  rear_left_leg:
      type: effort_controllers/JointPositionController
      joint: rear_left_leg
      pid: {p: 9, i: 0.03, d: 0.3055, i_clamp_min:  -1000, i_clamp_max: 1000}